# Generated by Django 2.2.4 on 2019-09-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=32)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
