# Generated by Django 2.2.4 on 2019-09-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32)),
                ('content', models.TextField(max_length=32)),
                ('dueDate', models.DateField(blank=True, null=True)),
                ('priority_flag', models.IntegerField(choices=[(0, ''), (1, 'Low'), (2, 'Normal'), (3, 'High')], default=0)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
